mysql:
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "root"
  password: "password"
  useSSL: false
  pool-size: 10


daily-login-bonus:
  enabled: true
  amount: "100"
  timezone: "Asia/Tokyo"

quest:
  rewards:
    task: "100"
    goal: "500"
    challenge: "1000"
